export const userContants = {
    USER_SIGN_UP_REQUEST: 'USER_SIGN_UP_REQUEST',
    USER_SIGN_UP_SUCCESS: 'USER_SIGN_UP_SUCCESS',
    USER_SIGN_UP_FAILURE: 'USER_SIGN_UP_FAILURE',
    USER_LOG_IN_REQUEST: 'USER_LOG_IN_REQUEST',
    USER_LOG_IN_SUCCESS: 'USER_LOG_IN_SUCCESS',
    USER_LOG_IN_FAILURE: 'USER_LOG_IN_FAILURE',
    USER_LOG_OUT_REQUEST: 'USER_LOG_OUT_REQUEST',
    USER_LOG_OUT_SUCCESS: 'USER_LOG_OUT_SUCCESS',
    USER_LOG_OUT_FAILURE: 'USER_LOG_OUT_FAILURE',
}